# .github/workflows/ci-cd.yml

name: CI/CD Build & Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Debug info
        run: |
          echo "=== Node version ==="
          node --version
          echo "=== NPM version ==="
          npm --version
          echo "=== Available scripts ==="
          npm run
          echo "=== TypeScript version ==="
          npx tsc --version

      - name: TypeScript compilation check
        run: npx tsc --noEmit

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Run tests (optional)
        run: npm run test
        continue-on-error: true

  # Job de déploiement optionnel - à adapter selon vos besoins
  # deploy:
  #   needs: build-test
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Deploy application
  #       run: |
  #         echo "Deploying application..."
  #         # Ajoutez ici vos commandes de déploiement
  #       env:
  #         DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
