# .github/workflows/ci-cd.yml

name: CI/CD Build & Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Debug info
        run: |
          echo "=== Node version ==="
          node --version
          echo "=== NPM version ==="
          npm --version
          echo "=== Available scripts ==="
          npm run
          echo "=== TypeScript version ==="
          npx tsc --version

      - name: TypeScript compilation check
        run: npx tsc --noEmit

      - name: Run linting
        run: npm run lint

      - name: Build application
        run: npm run build

      - name: Run tests (optional)
        run: npm run test
        continue-on-error: true

  docker-deploy:
    needs: build-test
    runs-on: ubuntu-latest
    name: Docker Build & Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose build

      - name: Test Docker Compose stack
        run: |
          docker compose up -d
          sleep 20
          curl --fail http://localhost:3000 || (docker compose logs app && exit 1)
          docker compose down

      - name: Show Docker info
        run: |
          echo "=== Docker image info ==="
          docker images pfe-backend
          echo "=== Docker container test ==="
          docker run --rm pfe-backend:latest node --version
          echo "=== Application build successful ==="

