# .github/workflows/ci-cd.yml

name: CI/CD Build & Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    name: Build & Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint

      - name: Run tests (if any)
        run: npm run test || echo "No unit tests found, skipping..."

      - name: Run e2e tests
        run: npm run test:e2e

      - name: Build application
        run: npm run build

  # Job de déploiement optionnel - à adapter selon vos besoins
  # deploy:
  #   needs: build-test
  #   runs-on: ubuntu-latest
  #   name: Deploy
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #
  #     - name: Deploy application
  #       run: |
  #         echo "Deploying application..."
  #         # Ajoutez ici vos commandes de déploiement
  #       env:
  #         DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
